### ISSUE TITLE
(EthernetSSLClient)(SSL_ERROR)(available): Cannot operate on a closed SSL connection.

### ISSUE THREAD

**Issue by simogaspa84** [khoih-prog/EthernetWebServer_SSL#26]
Hi @khoih-prog ...

I am getting this issue... 

Do you have an idea of the meaning and a possible way to fix it?

What should I check?

Thanks a lot

**Comment by khoih-prog** [comment]
HI @simogaspa84 

Please follow the guideline when posting any issue, such as [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example), etc. so that anybody can duplicate it. OTW, your post will be **ignored and deleted**.

First do some **basic research**, and you'll know what it means. Be independent first then you can learn a lot from the experience. Always start from the **known working** examples or previous codes.

https://github.com/khoih-prog/EthernetWebServer_SSL/blob/fc79ef0399f898ac6fa0f3897305d52cd6f85db0/src/SSLClient/SSLClient_Impl.h#L423-L433

Also ask the general questions on general Forums or [**OPEnSLab-OSU**](https://github.com/OPEnSLab-OSU/SSLClient/issues) if SSL- related, unless you're sure that it's a bug of this library.

Keep doing this way will get you blocked from accessing the library repo.

I'm sorry I don't have time in continuing to deal with the basic issue, and have to close it now to work on something else.
