### ISSUE TITLE
Build MQTTClient_SSL Error

### ISSUE THREAD

**Issue by Huynguyen97haui** [khoih-prog/EthernetWebServer_SSL#29]
### Describe the bug

Hi Mr. Khoi Hoang, i'm trying build MQTTClient_SSL example but i got some error, it's look like without some libraries. Can you help me fix it? Thank you so much! I appriciate!

### Screenshots
![image](https://user-images.githubusercontent.com/87764405/206390469-065ace72-eb15-48f0-99ac-0d4b894e1e64.png)

**Comment by khoih-prog** [comment]
Hi @Huynguyen97haui 

Please follow the minimal rule when posting an issue, especially this is possibly your problem, not library issue or bug.

Never post an unreadable image, you have to post [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example) and the compile error by `copy and paste` the text and wrapping within the `code tag` or `triple back-ticks`

The issue is closed now, and won't reopen until you post the issue in **correct format** and also **prove that is a bug / issue of the library.**
